apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: prova
  newName: leonardojr96/ci-sum-python
  newTag: ca8d88e33b8e28be4d199028eca9f06474d3a1dc
